modLoader = "javafml"
loaderVersion = ">=${forge_version}"
license = "${mod_license}"
issueTrackerURL = "https://github.com/Steveplays28/${mod_id}/issues"

[[mods]]
modId = "${mod_id}"
version = "${version}"
displayName = "${mod_name}"
authors = "Steveplays28"
description = '''
${mod_description}
'''
logoFile = "assets/${mod_namespace}/icon.png"
displayURL = "https://github.com/Steveplays28/${mod_id}"

[mc-publish]
loaders = ["forge", "neoforge"]
curseforge = "${curseforge_project_id}"
modrinth = "${modrinth_project_id}"

[[dependencies.${mod_id}]]
modId = "minecraft"
mandatory = true
versionRange = "${supported_minecraft_version}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "forge"
mandatory = true
versionRange = ">=${forge_version}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "architectury"
mandatory = true
versionRange = ">=${architectury_api_version}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "cloth_config"
mandatory = true
versionRange = ">=${cloth_config_version}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "sodium"
mandatory = false
versionRange = "*"
ordering = "NONE"
side = "CLIENT"

[[dependencies.${mod_id}]]
modId = "better-clouds"
mandatory = false
versionRange = "*"
ordering = "NONE"
side = "CLIENT"
